### ISSUE TITLE
Windows Installer not working

### ISSUE THREAD

**Issue by GJjoe** [navelpluisje/reasonus-install#1]
installer doesn't seems to do anything when clicking install reasonus

windows X64

**Comment by navelpluisje** [comment]
@GJjoe, that's true. There is an issue with copying the files. It is still a work in progress. I'm currently working on more fixes and some improvements. But thanx for mentioning it. For updates on releases etc you can also check: https://forum.cockos.com/showthread.php?t=240162.

**Comment by navelpluisje** [comment]
@GJjoe This should be fixed with the latest version, which can be found here: https://github.com/navelpluisje/reasonus-install/releases/tag/v0.1.0
