### ISSUE TITLE
Touch Automation not working

### ISSUE THREAD

**Issue by jlabs1** [navelpluisje/reasonus-install#14]
How to reproduce:
1) Turn on touch automation for a given track
2) Move the fader while keeping your finger on it
3) Look at Reaper mixer GUI and notice how it loses "connection" with the touched fader, as if the touch was a one shot move and not continually held.

I tested to make sure this wasn't just a problem with my hardware unit, as I went into Studio One and tried the same fader with Touch automation.

**Comment by navelpluisje** [comment]
Some extra questions:
* What controller do you use? The FaderPort 8, 16 or v2?
* What automation type is this occuring (Trim, Write, Latch, Touch)?

Thanx in advance

**Comment by jlabs1** [comment]
1) FP16
2) Just touch as far as I can tell since write and latch cede control to the fader until a change of automation mode occurs or playback position changes.

Also for what it's worth, it seems to recognize the initial touch when I put my finger on it without moving it.  Also, so long as I keep it in motion it works, it's just when I keep the fader in one place while still touching it that it tries to reset as if I'm no longer touching it.
![image](https://user-images.githubusercontent.com/1088751/185653840-89cb67a8-0d4b-4ea7-9a6b-e59c8d9437d6.png)
Notice in the image how when I keep it in motion, everything's fine, but then as soon as I try to keep the fader in place (with my finger still on it) that it resets back to where it was until I start moving it (all while not having lifted my finger off of the fader)

**Comment by navelpluisje** [comment]
Thanx for the extra info. Will see if I can find the issue. Will keep you posted here.

**Comment by jlabs1** [comment]
To add, here's a screenshot of initially putting my finger on the fader without trying to move it.  Now granted, I don't have the greatest motor skills so I might be slightly bumping the fader each time I put my finger on it, but for what it's worth it shows up as a volume change from -6.20 to -6.44.  What's notable is that this is a repeating pattern, so it might not just be me.  Just throwing that out there.  This is kinda getting into the weeds here but I thought I'd share because it deals with overall touch sensitivity and maybe it'd be useful to know.  Dunno.  Thanks for your hard work!

![image](https://user-images.githubusercontent.com/1088751/185654770-54d15d2e-ba2f-42b2-a856-7ee7746fd51d.png)

**Comment by jlabs1** [comment]
Ah-ha!  I got this for you:
![image](https://user-images.githubusercontent.com/1088751/185657427-38f8d98d-5c40-43e0-b9d9-9fc1d201f509.png)
So a Touch gets sent as a NoteOn message, in this case 00 for On, and 7F for off.
Here are all 16 faders of the FP16 on hardware device mode Studio One.

**Comment by jlabs1** [comment]
Solved!  It seems like the API was changed somewhere along the line.  Whereas you created FaderTouchX as widgets, (see below)

![image](https://user-images.githubusercontent.com/1088751/185660064-4dd9cde0-42d9-4208-abf8-737c6c0764f4.png)

apparently the API that came with your installation (I didn't try to install CSI 2.0 on top of it) had been changed to instead be 
![image](https://user-images.githubusercontent.com/1088751/185659998-fab4a0db-cda6-4fd0-bf8d-4836e20fbd4d.png)
So I went ahead and applied it to the FP16.mst file as such,
![image](https://user-images.githubusercontent.com/1088751/185660422-02ef8049-5c68-4136-a064-f9347d4bc3d7.png)
Result?
It works!
![image](https://user-images.githubusercontent.com/1088751/185659946-e1481429-df82-431b-9085-0c8a43c63594.png)

**Comment by navelpluisje** [comment]
Wow, thanx. My planning is to finnish a new release this weekend. Will include these changes right away.

CSI v2 will not work with ReaSonus. I'm now working together with Geoff to implement all the changes I had to make for the faderport in csi v2. We're making some nice progress there. Once everthing is in CSI v2 i will update all the files and create a new version.

But again, thank you so much for this.

**Comment by jlabs1** [comment]
You're very welcome!  By the way, thank you so much for putting this project together, it single-handedly brought me back to Reaper from Studio One!
