### ISSUE TITLE
Touch automation still broken

### ISSUE THREAD

**Issue by jlabs1** [navelpluisje/reasonus-install#16]
The problem exists in a clean install shipped with Reasonus.  I probably confused the issue by bringing up CSI 2.0, which I did only as a way of confirming that it was happening in a clean install of Reasonus, and not as a result of me going rogue and trying to fiddle around with using Reasonus in a CSI 2.0 install.

Here's the fix, 100% guaranteed.  
Wherever you have a FaderX widget,
> Widget Fader1
>   Fader14Bit e0 7f 7f
>   FB_Fader14Bit e0 7f 7f
> WidgetEnd

A third line has to be added as such
> Widget Fader1
>   Fader14Bit e0 7f 7f
>   FB_Fader14Bit e0 7f 7f
>   **Touch 90 68 7f 90 68 00**
> WidgetEnd

To be blunt: touch automation is literally broken in the version you have online right now.

Thanks again for the hard work!  I've been wanting to use my Faderport in Reaper for a very long time, and until Reasonus, I didn't have that spark of inspiration to get started.  I've made the switch and will not be looking back!

**Comment by navelpluisje** [comment]
Hmm, damn. You have a FP 16, right. Looks like I only did the FP 8 (that's what I have). Will change it right away.
Will let you know when it's done.

**Comment by jlabs1** [comment]
FP16, yup!  Thank you so much!

**Comment by navelpluisje** [comment]
Can you try this file? If this works I will create a new version

[FP16.txt](https://github.com/navelpluisje/reasonus-install/files/9434384/FP16.txt)

**Comment by jlabs1** [comment]
Works 100%!

**Comment by jlabs1** [comment]
All 16 channels confirmed!

**Comment by navelpluisje** [comment]
Can you run the installer again? No need for a new download. The installer will download the latest resource file.
In the about page, after install, it should say v1.0.1 for the resource files

**Comment by jlabs1** [comment]
![image](https://user-images.githubusercontent.com/1088751/186944419-52e1c3b7-8981-4949-81ac-c4bb35b40a48.png)
Hasn't updated on my end yet

**Comment by navelpluisje** [comment]
Ah, the resources were stiil marked as pre-release. Should work now.

**Comment by jlabs1** [comment]
That did it!  Thank you!!!

**Comment by navelpluisje** [comment]
You're welcome

**Comment by navelpluisje** [comment]
Cool, have to go now, but will release it this evening. Also the missing file will be added then
