### ISSUE TITLE
FaderPort Control broken on FP16

### ISSUE THREAD

**Issue by jlabs1** [navelpluisje/reasonus-install#17]
![image](https://user-images.githubusercontent.com/1088751/186937980-4f61f9c2-7103-457d-8838-2ee887289883.png)

**Comment by navelpluisje** [comment]
Thanx, will add it to the list

**Comment by jlabs1** [comment]
Thank you!  I'll keep you apprised of any FP16 issues I run into, which are really few and far in between besides this and the automation issue!

**Comment by jlabs1** [comment]
1.0.1 fixed it!
