### ISSUE TITLE
FAILED INSTALL?

### ISSUE THREAD

**Issue by wavemechanix** [navelpluisje/reasonus-install#22]
**Describe the bug**
  Installed Reasonus, restarted Reaper, no go. My faderport 16 was working with pretty good but limited functionality in MCU/Logic mode, now it's in Studio One mode as directed in instructions, it's 'waiting for host'.

OK I MIGHT HAVE FIXED THIS- SEE BELOW

**Operating System**
- [] Windows 10

**Versions**
Versions can be found on the About page of the installer
- Reasonus Installer: ...
- Reasonus Resources: .1.01
- CSI (ReaSonus): 1.1

**Expected behavior**
Expected a working control surface. It was working before in MCU mode but only 8 tracks not 16, also couldn't automate mutes though that could be user error. Now it's not connected but is 'waiting for host'.

**Additional context**

What do I choose in Preferences/Control Surfaces/OSC/Web control? Anything?
Update: I chose Control Surface Integrator, a new option added by the install I assume? There were no instructions that this needs to be chosen. Suggest adding this to instructions.

**Comment by navelpluisje** [comment]
To clarify, You needed to add the csi to the reaper surface settings?
If so, that should work. Plaese let me know

**Comment by wavemechanix** [comment]
I've narrowed the light issue down to the channels have to have a colour
selected for the buttons to light up at all and show as highlighted when
selected. Channels with just the default grey don't work. Guess I'll have
to add channel colours to my default setup. If they'd just show white when
selected that would do.

**Comment by wavemechanix** [comment]
Btw I've just finished mixing an album using the device and your program,
couldn't have done it without either as it required hundreds of rides and
fine adjustments. I'm still learning its capabilities, ie. editing plugins
etc. Thanks so much!
