### ISSUE TITLE
attempt to run FaderPort Control from within reaper- failed

### ISSUE THREAD

**Issue by wavemechanix** [navelpluisje/reasonus-install#23]
**Describe the bug**
attempt to run FaderPort Control from within reaper

**To Reproduce**
Followed instructions:
1) In the menu click Actions and the Show Action List…
2) Start typing reasonus faderport and press enter
The plugin should appear now:

Doesn't run, instead I get:

Message in dialog box: 
refFunctionAction.lua:135: attempt to call a nil value (field 'CF_GetCommandText')

**Operating System**
- [] Windows 10

**Versions**
Versions can be found on the About page of the installer
- Reasonus Installer: ...
- Reasonus Resources: ...1.01
- CSI (ReaSonus): .1.1

**Expected behavior**
expected to run FaderPort Control

**Screenshots**
![image](https://user-images.githubusercontent.com/113090531/200301321-50e30d1f-88d0-4c33-862f-d9ce31431e14.png)

**Additional context**
Thanks so much for this great.. whatever you call it, once it's running properly It'll be brilliant! Will be shouting you a few coffees for sure.

**Comment by navelpluisje** [comment]
Have you installed sws?
It looks like you do not have sws installed, because this missing function is part of SWS.
If you haven't please check this: https://www.sws-extension.org/

**Comment by wavemechanix** [comment]
Yes, that was the problem. It's running great now, thank you. Only thing is the SELECT buttons don't light up as expected, compared to say when running Studio One. They still work but I can't tell which is selected without checking Reaper.

**Comment by navelpluisje** [comment]
Will check the select buttons.
