### ISSUE TITLE
Faderport V2 buttons not working

### ISSUE THREAD

**Issue by maldomusica** [navelpluisje/reasonus-install#30]
**Describe the bug**
I installed the Reasonus 1.01 but nothing changes in my FPv2 (single fader). The bypass, shift, link, channel, scroll, master, click, section and marker buttons don't work.

The fader has the same behavior since before installing Reasonus. I have Presonus FaderportV2 selected in Control Surface Tab. I don't know if "Reasonus Faderport" should appear on the tab but nothing appears for me.

**To Reproduce**
Only installing Reasonus

**Operating System**
- [] Windows 10

**Versions**
- Reasonus Installer: ...
- Reasonus Resources: 1.01
- CSI (ReaSonus): 1.1

**Expected behavior**
I thought the Faderport buttons would work fully, just like in Studio One.

**Screenshots**
![reasonus 1](https://user-images.githubusercontent.com/62590022/213888461-6f547c8d-a4cc-4fdd-931d-756bef88becb.png)
![reasonus 2](https://user-images.githubusercontent.com/62590022/213888467-9c11667d-1ff5-40b5-a379-b86bdef54198.png)

**Comment by maldomusica** [comment]
Ok I saw in other post that I had to select Control Surface Integrator instead of Faderport V2. Now buttons are working like the documentation says.

But, I found another problem. The fader doesn't access channels when they are hidden in the TCP (they are visible in the console). Temporal solution is show all channels in both TCP and MCP on the Track Manager.

**Comment by navelpluisje** [comment]
That's 'by design' and something that is in CSI v1.1. There stil are plans for porting everything, but currently I have a lot of ither stuff going on and porting to v2 has a lower priority for me right now.

Sorry about that
