### ISSUE TITLE
CSI Not Logging All Buttons on FaderPort v2

### ISSUE THREAD

**Issue by stvamgn** [navelpluisje/reasonus-install#33]
**Describe the bug**
-My Faderport v2 firmware is v3.51 (latest)
-My Reaper install is v6.73
-My SWS Extensions is v2.12.1.3
-Faderport v2 is disabled in MIDI devices
-Issue: Not all buttons work. The fader works, the transport does too. None of the function buttons do anything. I have attempted to troubleshoot by using the Action "CSI Toggle Show Raw Input from Surfaces". I can see CSI logging things like the fader, transport buttons but the "Shift" key isn't logging and as a result, none of the function keys either. In short, I am expecting the Faderport v2 to behave as the documentation indicates in section 4, but it doesn't.

**Operating System**
- [10.13.6] Mac OS

**Versions**
Versions can be found on the About page of the installer
- Reasonus Installer: no version displayed (weird?)
- Reasonus Resources: 1.0.1
- CSI (ReaSonus): 1.1 (reasonus-edition)

**Comment by stvamgn** [comment]
I'm a noob. I just discovered that my Faderport v2 was NOT is "StudioOne" mode. As soon as I turned it off, held Next while turning it on, then hit Solo, I opened Reaper again and now all the buttons are working as the documentation indicates. Apologies gents.

**Comment by navelpluisje** [comment]
No worries. Glad you figured it out
