### ISSUE TITLE
Clarify Reaper Forum

### ISSUE THREAD

**Issue by petn** [navelpluisje/reasonus-install#51]
It seems you have been here these days (have you?), please go to Reaper Forum and clarify that ReaSonus is not working with current CSI version. There is a massive confusion about your ReaSonus install. I am shure people understand if you are too busy to keep up with the changes, but please remove the impression that everything works like a charm, cause it does not.

Thanks.

**Comment by navelpluisje** [comment]
Done, Check ;-)
