### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by Sciss** [navelpluisje/reasonus-install#63]
Hi there. How can I install this software on Linux? I'm running native Linux Reaper, and would like to get going with the Faderport 8. My understand is, this would work with your software. The releases has only Mac/Windows binaries, but none for Linux or build instructions for Linux. Thanks!

**Comment by navelpluisje** [comment]
Hi @Sciss ,
It does not. It is technically a wrapper around CSI, which does not support Linux.
I've had some ideas of making it all native, but my c(++) skills are not really great.

Sorry for that.

**Comment by Sciss** [comment]
Oh I see. Perhaps you could help me, still. I'm trying to understand what the native Faderport code does to tell the device to boot up. If I just launch it, it stays in 'Waiting for host'. I was looking through GitHub for pointers, and I thought there must be something in your code perhaps, since I read somewhere that native Faderport 8 is supported. In the meantime, I managed to connect the FP 8 via Ardour, so that also has a functioning native implementation. Still wondering, what that handshake is that you need to make the device happy.

**Comment by navelpluisje** [comment]
In reaper in the settings therre is an item: `Control/OSC/Web`. In there you should add a device. You could for instance select Presonus Faderport. Then you have to select the midi in and out.
That should be it. This support is pretty minimal though.
Also should the faderport in the midi device list set to disabled

**Comment by Sciss** [comment]
I solved the mystery with the FP 8 usage; just seemed a problem of how SuperCollider connects to the MIDI output. I got it working now, there is no such thing as a handshake.
